name: plant_ecommerce
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  provider: ^6.1.2
  intl_phone_number_input: ^0.7.1
  intl: ^0.17.0
  flutter_holo_date_picker: ^1.1.0
  get: ^4.6.5
  carousel_slider: ^4.1.1
  sizer: ^2.0.15




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans/Italic.ttf
          style: italic
        - asset: assets/fonts/JosefinSans/Bold.ttf
        - asset: assets/fonts/JosefinSans/Medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Medium.ttf
        - asset: assets/fonts/Montserrat/Regular.ttf
        - asset: assets/fonts/Montserrat/Italic.ttf
        - asset: assets/fonts/Montserrat/Bold.ttf
          weight: 700
